services:
  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    # Port exposé pour Nginx, pas pour le développement local
    ports:
      - "5173:80"  # Il est possible de l'ajuster pour la prod, mais pour le dev c'est correct
    depends_on:
      - backend
    networks:
      - clubmanager

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app  # Synchronisation des fichiers locaux avec le conteneur
    networks:
      - clubmanager

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Fichier principal de configuration Nginx
      - ./nginx/conf.d:/etc/nginx/conf.d  # Dossier pour les configurations supplémentaires
    ports:
      - "80:80"  # Serveur frontend via Nginx sur le port 80
    depends_on:
      - frontend
      - backend
    networks:
      - clubmanager

networks:
  clubmanager:
    driver: bridge
